[WIP] Attempt to fix `swift test` working around SR-14008.
https://bugs.swift.org/browse/SR-14008

`swift test` fails:

```
$ DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2020-12-23-a.xctoolchain/usr/lib/swift/macosx swift test
2020-12-30 14:29:55.586 xctest[20925:26997481] The bundle “SwiftDifferentiationPackageTests.xctest” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2020-12-30 14:29:55.586 xctest[20925:26997481] (dlopen_preflight(/Users/danielzheng/Differentiation/.build/x86_64-apple-macosx/debug/SwiftDifferentiationPackageTests.xctest/Contents/MacOS/SwiftDifferentiationPackageTests): Library not loaded: /usr/lib/swift/libswift_Differentiation.dylib
  Referenced from: /Users/danielzheng/Differentiation/.build/x86_64-apple-macosx/debug/SwiftDifferentiationPackageTests.xctest/Contents/MacOS/SwiftDifferentiationPackageTests
  Reason: image not found)
```

This was an attempt to:
- Remove `apple/swift-numerics` as a dependency, since it imports
  `_Differentiation` module from toolchains. This did not fix the error above.

- Temporarily delete `libswift_Differentiation.dylib` from the development
  snapshot toolchain. This produces a new error, which @compnerd said was related
  to autolinking of the `_Differentiation` module:

```console
$ swift test -Xcc -I$HOME/Library/tensorflow-2.3.0/usr/include -Xlinker -L$HOME/Library/tensorflow-2.3.0/usr/lib -Xswiftc -DTENSORFLOW_USE_STANDARD_TOOLCHAIN -Xlinker -rpath -Xlinker $HOME/Library/tensorflow-2.3.0/usr/lib
ld: warning: dylib (/Users/danielzheng/Library/tensorflow-2.3.0/usr/lib/libx10.dylib) was built for newer macOS version (10.15) than being linked (10.13)
ld: warning: Could not find or use auto-linked library 'swift_Differentiation'
Undefined symbols for architecture x86_64:
  "_$s16_Differentiation14DifferentiableP28zeroTangentVectorInitializer0dE0QzycvgTj", referenced from:
      _$s10TensorFlow12RNNCellInputV13TangentVectorV04zeroeF11InitializerAEyxq__Gycvg in Recurrent.swift.o
      _$s10TensorFlow12RNNCellInputV28zeroTangentVectorInitializerAC0fG0Vyxq__Gycvg in Recurrent.swift.o
      _$s10TensorFlow13RNNCellOutputV13TangentVectorV04zeroeF11InitializerAEyxq__Gycvg in Recurrent.swift.o
      _$s10TensorFlow13RNNCellOutputV28zeroTangentVectorInitializerAC0fG0Vyxq__Gycvg in Recurrent.swift.o
      _$s10TensorFlow14RecurrentLayerV13TangentVectorV04zeroeF11InitializerAEyx_Gycvg in Recurrent.swift.o
      _$s10TensorFlow14RecurrentLayerV28zeroTangentVectorInitializerAC0fG0Vyx_Gycvg in Recurrent.swift.o
      _$s10TensorFlow10SequentialV13TangentVectorV04zerodE11InitializerAEyxq__Gycvg in Sequential.swift.o
      ...
  "_$s16_Differentiation14DifferentiableP28zeroTangentVectorInitializer0dE0QzycvgTq", referenced from:
      _$s10TensorFlow0A0VyxG16_Differentiation14DifferentiableA2A0aB13FloatingPointRzrlMc in Tensor.swift.o
      _$s10TensorFlow18EmptyTangentVectorV16_Differentiation14DifferentiableAAMc in Layer.swift.o
      _$s10TensorFlow6Conv1DV13TangentVectorVyx_G16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      _$s10TensorFlow6Conv1DVyxG16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      _$s10TensorFlow6Conv2DV13TangentVectorVyx_G16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      _$s10TensorFlow6Conv2DVyxG16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      _$s10TensorFlow6Conv3DV13TangentVectorVyx_G16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      ...
  "_$s16_Differentiation14DifferentiableP4move5alongy13TangentVectorQz_tFTj", referenced from:
      _$s10TensorFlow12RNNCellInputV4move5alongyAC13TangentVectorVyxq__G_tF in Recurrent.swift.o
      _$s10TensorFlow13RNNCellOutputV4move5alongyAC13TangentVectorVyxq__G_tF in Recurrent.swift.o
      _$s10TensorFlow14RecurrentLayerV4move5alongyAC13TangentVectorVyx_G_tF in Recurrent.swift.o
      _$s10TensorFlow10SequentialV4move5alongyAC13TangentVectorVyxq__G_tF in Sequential.swift.o
      _$s10TensorFlow7RMSPropC6update_5alongyxz_13TangentVectorQztF in MomentumBased.swift.o
      _$s10TensorFlow7AdaGradC6update_5alongyxz_13TangentVectorQztF in MomentumBased.swift.o
      _$s10TensorFlow8AdaDeltaC6update_5alongyxz_13TangentVectorQztF in MomentumBased.swift.o
      ...
  "_$s16_Differentiation14DifferentiableP4move5alongy13TangentVectorQz_tFTq", referenced from:
      _$s10TensorFlow0A0VyxG16_Differentiation14DifferentiableA2A0aB13FloatingPointRzrlMc in Tensor.swift.o
      _$s10TensorFlow18EmptyTangentVectorV16_Differentiation14DifferentiableAAMc in Layer.swift.o
      _$s10TensorFlow6Conv1DV13TangentVectorVyx_G16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      _$s10TensorFlow6Conv1DVyxG16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      _$s10TensorFlow6Conv2DV13TangentVectorVyx_G16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      _$s10TensorFlow6Conv2DVyxG16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      _$s10TensorFlow6Conv3DV13TangentVectorVyx_G16_Differentiation14DifferentiableAAMc in Convolutional.swift.o
      ...
ld: symbol(s) not found for architecture x86_64
[1/39] Linking libTensorFlow.dylib
error: fatalError
```